version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./leadrescue/backend:/app
    env_file:
      - ./leadrescue/backend/.env.sample
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./leadrescue/frontend:/app
